###
# В то время как запрос match_all возвращает все результаты 
# из индекса или нескольких индексов, противоположный 
# запрос match_none не возвращает никаких результатов.



GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "match_none": {}
    }
}

###
# Допустим, у нас есть функция приложения, которая позволяет 
# администраторам «заблокировать» базу данных фильмов 
# для обслуживания или обновлений. Когда база данных 
# заблокирована, вы хотите, чтобы все поисковые запросы 
# не возвращали результатов, а не выдавали ошибочные 
# результаты. В этом случае вы можете вставить запрос 
# match_none на основе условия блокировки в вашем приложении. 
# Запрос bool, написанный в фрагменте ниже, демонстрирует 
# такой вариант использования: 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "bool":{
            "must": [ 
                {"match_none": {}}
            ]
        }
    }
}
