###
# Значение tie_breaker — это положительное число с плавающей 
# точкой от 0,0 до 1,0 (по умолчанию — 0,0). В этом случае 
# мы умножаем баллы нелучших полей на tiebreaker и добавляем 
# результат к баллу каждого документа, который соответствует 
# нескольким полям. Последний составной запрос, который 
# мы рассмотрим в этой главе, — это запрос оценки функции. 
# Он дает нам гораздо больше гибкости при назначении 
# баллов на основе наших потребностей с использованием 
# предопределенных функций. 
GET {{baseUrl}}/products/_search
Authorization: {{auth}}
content-type: application/json

{
    "_source": [
        "type",
        "overview"
    ],
    "query": {
        "dis_max": {
            "queries": [
                {
                    "match": {
                        "type": "smart tv"
                    }
                },
                {
                    "match": {
                        "overview": "smart tv"
                    }
                }
            ],
            "tie_breaker": 0.5
        }
    }
}
