###
# Иногда мы хотим присвоить оценку возвращаемому документу 
# из поискового запроса на основе внутренних требований, 
# таких как придание веса определенному полю или отображение 
# рекламы спонсора на основе случайной оценки релевантности. 
# Запросы оценки функции (function_score) помогают создать 
# оценку на основе определяемых пользователем функций, 
# включая случайные, основанные на скриптах или функции 
# распада (Гаусса, линейные и т. д.). 
GET {{baseUrl}}/products/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "function_score": {
            "query": {
                "term": {
                    "product": "tv"
                }
            },
            "random_score": {}
        }
    }
}

###
# Что, если у нас есть требование воспроизвести случайную 
# оценку, чтобы независимо от того, сколько раз мы выполняем 
# один и тот же запрос, случайно сгенерированная оценка 
# всегда была той же? Для этой цели мы можем настроить 
# функцию random_score, заполнив ее начальным значением 
# и значениями полей. В следующем листинге показан запрос 
# с функцией random_score, инициализированной начальным 
# значением. 
GET {{baseUrl}}/products/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "function_score": {
            "query": {
                "term": {
                    "product": "tv"
                }
            },
            "random_score": {
                "seed": 10,
                "field":"user_ratings"
            }
        }
    }
}