# Запрос match_phrase ожидает полную фразу: фразу, в которой 
# нет пропущенных слов. Однако пользователи не 
# всегда могут вводить точные фразы. Чтобы 
# справиться с этим, решение Elasticsearch 
# заключается в установке параметра slop для 
# запроса match_phrase: положительного целого числа, 
# указывающего, сколько слов фразы отсутствует 
# при поиске. Следующий запрос имеет slop, 
# равный 2, что указывает на то, что 
# поисковый запрос может ожидать, что до 
# двух слов будут либо пропущены, 
# либо не будут в порядке при выполнении запроса.

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": { 
        "match_phrase": { 
            "synopsis": {
                "query": "must-have book Java programmer",
                "slop": 3
            }
        } 
    } 
}
