# Найти все документы, автором которых является Джошуа, 
# с использованием префикса.

# Значение запроса должно быть указано строчными буквами, 
# поскольку префиксный запрос — это запрос на уровне термина.

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "prefix": {
            "author": "josh"
        }
    }
}