# Найти все документы, автором которых является Джошуа, 
# во всех книгах в нашем индексе.

# Можно искать в разном регистре, будет находить всегда, кроме сокращённого.
# "author":"JoShUa" 
# "author":"joshua" (or "JOSHUA") 
# "author":"Bloch"
# Для поиска по сокращённому необходимо использовать префикс "Поиск книги с использованием префикса"

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "match": {
            "author": "joshua"
        }
    }
}