# Elasticsearch работает довольно усердно, 
# чтобы найти сходство между словами, используя 
# алгоритм расстояния редактирования Левенштейна.

# Если нечеткость установлена ​​на 1, одна орфографическая 
# ошибка (одна буква не на своем месте, пропущена 
# или добавлена) может быть прощена.

# fuzziness - размытость

# Функция нечеткости не просто изменяет слово; 
# она вставляет и удаляет символы 
# для соответствия словам.

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": { 
        "match": { 
            "tags": {
                "query": "Komputer Pogramming ",
                "fuzziness": 1
            }
        } 
    } 
}
