# В дополнение к полнотекстовым запросам Elasticsearch 
# поддерживает запросы для поиска 
# структурированных данных: запросы на уровне терминов.
# Запросы на уровне терминов помогают нам искать 
# структурированные данные, такие как числа, 
# даты, IP-адреса и т. д.

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "_source": ["title","edition"],
    "query": { 
        "term": { 
            "edition": {
                "value": 3
            }
        } 
    } 
}
