# Запрос диапазона можно применять к 
# датам, числам и другим атрибутам, что делает 
# его мощным помощником при поиске данных диапазона.

# must
# Предложение must означает, что критерии поиска в 
# запросе должны соответствовать документам. 
# Положительное совпадение повышает оценку 
# релевантности. Мы строим предложение must 
# с максимально возможным количеством листовых запросов.

# must_not
# В пункте must_not критерии не должны соответствовать 
# документам. Этот пункт не влияет на оценку 
# (он выполняется в контексте выполнения фильтра)

# should
# Не обязательно, чтобы критерий, определенный 
# в пункте «должен», совпадал. 
# Однако, если он совпадает, 
# показатель релевантности повышается.

# filter
# В пункте фильтра критерии должны соответствовать 
# документам, аналогично пункту must. Единственное 
# отличие состоит в том, что оценка не имеет значения 
# в пункте фильтра (она выполняется в контексте 
# выполнения фильтра).

POST {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "_source": ["title","amazon_rating"],
    "query": { 
        "bool": { 
            "must": [],
            "must_not": [],
            "should": [],
            "filter": []
        } 
    } 
}
