# КРАСНЫЙ — Шарды еще не назначены, поэтому не все данные доступны 
# для запроса. Обычно это происходит при запуске кластера, 
# в течение которого шарды находятся в переходном состоянии.

# ЖЕЛТЫЙ — Реплики еще не назначены, но все шарды назначены 
# и находятся в действии. Это может произойти, когда узлы, 
# на которых размещены реплики, вышли из строя или 
# только начинают работу.

# ЗЕЛЕНЫЙ — Это счастливое состояние, 
# когда все сегменты и реплики назначены и 
# работают так, как и ожидалось.

GET {{baseUrl}}/_cluster/health
Authorization: {{auth}}
content-type: application/json


### 

GET {{baseUrl}}/_cat/health
Authorization: {{auth}}
content-type: application/json