# Удаление индексов --------------------------
### 
DELETE {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json
# --------------------------------------------

###
POST {{baseUrl}}/111/_doc/1
Authorization: {{auth}}
content-type: application/json

{
    "title":"Avatar",
    "actors": ["Denis"],
    "rating":9.3,
    "rating_amazon":4.5,
    "rating_rotten_tomatoes":80,
    "rating_metacritic":90
}

###
POST {{baseUrl}}/111/_update/1
Authorization: {{auth}}
content-type: application/json

{
    "script": {
        "source": "ctx._source.runtime_in_minutes = 175;ctx._source.metacritic_rating= 100;ctx._source.tomatometer = 97;"
    }
}

### 
GET {{baseUrl}}/111/_doc/1
Authorization: {{auth}}
content-type: application/json
