# Удаление индексов --------------------------
### 
DELETE {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

# --------------------------------------------

###
POST {{baseUrl}}/111/_doc/1
Authorization: {{auth}}
content-type: application/json

{"title": "Elasticsearch in Action"}

###
GET {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json