# Удаление индексов --------------------------
### 
DELETE {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

# --------------------------------------------

### 
PUT {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

{
     "settings": {
        "analysis": {
            "analyzer": {
                "pattern_analyzer":{
                    "type":"pattern",
                    "pattern": "[-]",
                    "lowercase": true
                }
            }
        }
     }
}


### 
# ["1234","5678","9000","0000"]
GET {{baseUrl}}/111/_analyze
Authorization: {{auth}}
content-type: application/json

{
    "analyzer": "pattern_analyzer",
    "text": ["1234-5678-9000-0000"]
}