# Удаление индексов --------------------------
### 
DELETE {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

# --------------------------------------------

### 
# Если мы предоставим слово длиной 13 символов, 
# оно будет разделено на два токена по семь и 
# шесть символов (например, «Elasticsearch» станет 
# «Elastic», «search»).
PUT {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

{
     "settings": {
        "analysis": {
            "analyzer": {
                "standard_max_token_length":{
                    "type":"standard",
                    "max_token_length":7
                }
            }
        }
     }
}


### 
# ["lukša","s","k","s","in","action"]
GET {{baseUrl}}/111/_analyze
Authorization: {{auth}}
content-type: application/json

{
    "analyzer": "simple",
    "text": ["Lukša's K8s in Action"]
}