### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "multi_match": {
            "query": "Java",
            "fields": ["synopsis","title"]
        }
    }
}

### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "size": 0,
    "aggs": {
        "amazon_rating": {
            "avg": {
                "field": "amazon_rating"
            }
        }
    }
}