### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "_source": ["title*", "amazon_rating"],
    "query": {
        "match": {
            "title": "Java"
        }
    },
    "highlight": {
        "fields": {
            "title": {}
        }
    }
}

### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "_source": {
        "includes": ["title*","synopsis","genre"],
        "excludes": ["title.original"]
    },
    "query": {
        "match": {
            "title": "Java"
        }
    },
    "highlight": {
        "fields": {
            "title": {}
        }
    }
}
