### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "exists": {
            "field": "title2"
        }
    },
    "highlight": {
        "fields": {
            "title": {}
        }
    }
}


### 
GET {{baseUrl}}/books/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "exists": {
            "field": "title"
        }
    },
    "highlight": {
        "fields": {
            "title": {}
        }
    }
}