# Удаление индексов --------------------------
### 
DELETE {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json
# --------------------------------------------

###
# PUT {{baseUrl}}/111
# Authorization: {{auth}}
# content-type: application/json

# {
#     "mappings": {
#        "properties": {
#             "title":{
#                 "type": "text",
#                 "index_prefixes":{}
#             }
#        } 
#     }
# }

###
GET {{baseUrl}}/111
Authorization: {{auth}}
content-type: application/json

###
POST {{baseUrl}}/111/_doc/1
Authorization: {{auth}}
content-type: application/json

{
    "title":"Avatar"
}

###
GET {{baseUrl}}/111/_search
Authorization: {{auth}}
content-type: application/json

###
# Это может быть неуклюжим способом обработки, поскольку 
# мы можем не знать, неправильно ли набрал пользователь 
# одну букву или несколько букв. Вот почему Elasticsearch 
# предоставляет настройку по умолчанию для нечеткости: 
# настройку AUTO. Если атрибут нечеткости не указан, 
# предполагается настройка по умолчанию AUTO. Настройка 
# AUTO определяет расстояние редактирования на основе 
# длины слова, как показано в таблице 9.3. Придерживаться 
# настройки по умолчанию AUTO для атрибута нечеткости 
# предпочтительнее, если только мы не знаем точный вариант 
# использования в данный момент.

# Использование настройки размытости AUTO
# 0 to 2 - 0 - Если слово короче двух символов, нечеткость не применяется. Это означает, что неправильно написанные слова не могут быть исправлены.
# 3 to 5 - 1 - Если длина слова составляет от 3 до 5 символов, применяется расстояние редактирования 1.
# More than 5 - 3 - Если длина слова превышает 5 символов, применяется расстояние редактирования 2.

GET {{baseUrl}}/111/_search
Authorization: {{auth}}
content-type: application/json

{
    "query": {
        "fuzzy": {
            "title": {
                "value": "aatar",
                "fuzziness": "AUTO"
            }
        }
    },
    "highlight": {
        "fields": {
            "title": {}
        }
    }
}
